[project]
name = "photoalbum"
version = "0.1.0"
description = "Python script to organize your photos."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyinstaller>=6.12.0",
    "pytest>=8.3.4",
    "typer>=0.15.1",
]
